/* Generated by MyraPad at 9/2/2023 8:23:47 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ModelViewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textPath = new TextBox();
			_textPath.Readonly = true;
			_textPath.Width = 300;
			_textPath.Id = "_textPath";

			_buttonChange = new TextButton();
			_buttonChange.Text = "Change...";
			_buttonChange.Id = "_buttonChange";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_textPath);
			horizontalStackPanel1.Widgets.Add(_buttonChange);

			var listItem1 = new ListItem();

			var listItem2 = new ListItem();
			listItem2.Text = "Move";

			var listItem3 = new ListItem();
			listItem3.Text = "Attack";

			_comboAnimations = new ComboBox();
			_comboAnimations.Id = "_comboAnimations";
			_comboAnimations.Items.Add(listItem1);
			_comboAnimations.Items.Add(listItem2);
			_comboAnimations.Items.Add(listItem3);

			_buttonPlayStop = new TextButton();
			_buttonPlayStop.Text = "Play";
			_buttonPlayStop.Width = 100;
			_buttonPlayStop.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_buttonPlayStop.Id = "_buttonPlayStop";

			_sliderTime = new HorizontalSlider();
			_sliderTime.Width = 300;
			_sliderTime.Id = "_sliderTime";

			_labelTime = new Label();
			_labelTime.Text = "0.0";
			_labelTime.Id = "_labelTime";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(_buttonPlayStop);
			horizontalStackPanel2.Widgets.Add(_sliderTime);
			horizontalStackPanel2.Widgets.Add(_labelTime);

			_checkBoxShowBoundingBoxes = new CheckBox();
			_checkBoxShowBoundingBoxes.Text = "Show Bounding Boxes";
			_checkBoxShowBoundingBoxes.Id = "_checkBoxShowBoundingBoxes";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_comboAnimations);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(_checkBoxShowBoundingBoxes);

			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel2.Widgets.Add(_labelFps);
			verticalStackPanel2.Widgets.Add(_labelMeshes);
			verticalStackPanel2.Widgets.Add(_labelCamera);

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(verticalStackPanel2);
		}

		
		public TextBox _textPath;
		public TextButton _buttonChange;
		public ComboBox _comboAnimations;
		public TextButton _buttonPlayStop;
		public HorizontalSlider _sliderTime;
		public Label _labelTime;
		public CheckBox _checkBoxShowBoundingBoxes;
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
	}
}
