/* Generated by MyraPad at 16.10.2019 1:16:52 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace SampleScene.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";
			_labelMeshes.GridRow = 1;

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";
			_labelCamera.GridRow = 2;

			var grid1 = new Grid();
			grid1.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid1.Widgets.Add(_labelFps);
			grid1.Widgets.Add(_labelMeshes);
			grid1.Widgets.Add(_labelCamera);

			
			Widgets.Add(grid1);
		}

		
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
	}
}