/* Generated by MyraPad at 11.09.2019 21:23:24 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace ModelViewer.UI
{
	partial class MainPanel
	{
		private void BuildUI()
		{
			_checkLightning = new CheckBox();
			_checkLightning.Text = "Lightning On";
			_checkLightning.Id = "_checkLightning";

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.ColumnsProportions.Add(new Grid.Proportion());
			grid1.RowsProportions.Add(new Grid.Proportion());
			grid1.Widgets.Add(_checkLightning);

			_labelFps = new TextBlock();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new TextBlock();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";
			_labelMeshes.GridRow = 1;

			_labelCamera = new TextBlock();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";
			_labelCamera.GridRow = 2;

			var grid2 = new Grid();
			grid2.ColumnsProportions.Add(new Grid.Proportion());
			grid2.ColumnsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.RowsProportions.Add(new Grid.Proportion());
			grid2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			grid2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid2.Widgets.Add(_labelFps);
			grid2.Widgets.Add(_labelMeshes);
			grid2.Widgets.Add(_labelCamera);

			
			Widgets.Add(grid1);
			Widgets.Add(grid2);
		}

		
		public CheckBox _checkLightning;
		public TextBlock _labelFps;
		public TextBlock _labelMeshes;
		public TextBlock _labelCamera;
	}
}