/* Generated by MyraPad at 25.09.2019 0:15:11 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace SampleScene.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_labelFps = new TextBlock();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new TextBlock();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";
			_labelMeshes.GridRow = 1;

			_labelCamera = new TextBlock();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";
			_labelCamera.GridRow = 2;

			var grid1 = new Grid();
			grid1.ColumnsProportions.Add(new Proportion());
			grid1.ColumnsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid1.Widgets.Add(_labelFps);
			grid1.Widgets.Add(_labelMeshes);
			grid1.Widgets.Add(_labelCamera);

			
			Widgets.Add(grid1);
		}

		
		public TextBlock _labelFps;
		public TextBlock _labelMeshes;
		public TextBlock _labelCamera;
	}
}