/* Generated by MyraPad at 18.09.2019 23:32:37 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace NursiaStudio.UI
{
	partial class MainForm
	{
		private void BuildUI()
		{
			_menuItemQuit = new MenuItem();
			_menuItemQuit.Id = "_menuItemQuit";
			_menuItemQuit.Text = "&Quit";

			var menuItem1 = new MenuItem();
			menuItem1.Id = "";
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemQuit);

			_menuItemAddModel = new MenuItem();
			_menuItemAddModel.Id = "_menuItemAddModel";
			_menuItemAddModel.Text = "&Model";

			_menuItemAddSkybox = new MenuItem();
			_menuItemAddSkybox.Id = "_menuItemAddSkybox";
			_menuItemAddSkybox.Text = "&Skybox";

			_menuItemAddTerrain = new MenuItem();
			_menuItemAddTerrain.Id = "_menuItemAddTerrain";
			_menuItemAddTerrain.Text = "&Terrain";

			_menuItemAddWater = new MenuItem();
			_menuItemAddWater.Id = "_menuItemAddWater";
			_menuItemAddWater.Text = "&Water";

			var menuItem2 = new MenuItem();
			menuItem2.Id = "";
			menuItem2.Text = "&Items";
			menuItem2.Items.Add(_menuItemAddModel);
			menuItem2.Items.Add(_menuItemAddSkybox);
			menuItem2.Items.Add(_menuItemAddTerrain);
			menuItem2.Items.Add(_menuItemAddWater);

			_menuItemShowGrid = new MenuItem();
			_menuItemShowGrid.Id = "_menuItemShowGrid";
			_menuItemShowGrid.Text = "&Grid";

			_menuItemLockFps = new MenuItem();
			_menuItemLockFps.Id = "_menuItemLockFps";
			_menuItemLockFps.Text = "&Lock FPS at 60";

			var menuItem3 = new MenuItem();
			menuItem3.Id = "";
			menuItem3.Text = "&Options";
			menuItem3.Items.Add(_menuItemShowGrid);
			menuItem3.Items.Add(_menuItemLockFps);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Id = "_menuItemAbout";
			_menuItemAbout.Text = "&About";

			var menuItem4 = new MenuItem();
			menuItem4.Id = "";
			menuItem4.Text = "&Help";
			menuItem4.Items.Add(_menuItemAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(menuItem2);
			horizontalMenu1.Items.Add(menuItem3);
			horizontalMenu1.Items.Add(menuItem4);

			var listItem1 = new ListItem();
			listItem1.Id = "";
			listItem1.Text = "Directional Light (#_sun)";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "Camera (#_mainCamera)";

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "Terrain (#_terrain)";

			var listItem4 = new ListItem();
			listItem4.Id = null;
			listItem4.Text = "Water (#_water)";

			_listExplorer = new ListBox();
			_listExplorer.Id = "_listExplorer";
			_listExplorer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listExplorer.Items.Add(listItem1);
			_listExplorer.Items.Add(listItem2);
			_listExplorer.Items.Add(listItem3);
			_listExplorer.Items.Add(listItem4);

			_panelScene = new Panel();
			_panelScene.Id = "_panelScene";
			_panelScene.GridColumn = 2;

			_panelProperties = new Panel();
			_panelProperties.Id = "_panelProperties";
			_panelProperties.GridColumn = 4;

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(_listExplorer);
			_topSplitPane.Widgets.Add(_panelScene);
			_topSplitPane.Widgets.Add(_panelProperties);

			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";
			_labelMeshes.GridRow = 1;

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";
			_labelCamera.GridRow = 2;

			var grid1 = new Grid();
			grid1.ColumnsProportions.Add(new Proportion());
			grid1.ColumnsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.RowsProportions.Add(new Proportion());
			grid1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			grid1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			grid1.Widgets.Add(_labelFps);
			grid1.Widgets.Add(_labelMeshes);
			grid1.Widgets.Add(_labelCamera);

			var panel1 = new Panel();
			panel1.GridRow = 1;
			panel1.Widgets.Add(_topSplitPane);
			panel1.Widgets.Add(grid1);

			
			RowsProportions.Add(new Proportion());
			RowsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(horizontalMenu1);
			Widgets.Add(panel1);
		}

		
		public MenuItem _menuItemQuit;
		public MenuItem _menuItemAddModel;
		public MenuItem _menuItemAddSkybox;
		public MenuItem _menuItemAddTerrain;
		public MenuItem _menuItemAddWater;
		public MenuItem _menuItemShowGrid;
		public MenuItem _menuItemLockFps;
		public MenuItem _menuItemAbout;
		public ListBox _listExplorer;
		public Panel _panelScene;
		public Panel _panelProperties;
		public HorizontalSplitPane _topSplitPane;
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
	}
}