/* Generated by MyraPad at 8/12/2023 11:53:53 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace ModelViewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textPath = new TextBox();
			_textPath.Readonly = true;
			_textPath.Width = 300;
			_textPath.Id = "_textPath";

			_buttonChange = new TextButton();
			_buttonChange.Text = "Change...";
			_buttonChange.Id = "_buttonChange";

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_textPath);
			horizontalStackPanel1.Widgets.Add(_buttonChange);

			var listItem1 = new ListItem();

			var listItem2 = new ListItem();
			listItem2.Text = "Move";

			var listItem3 = new ListItem();
			listItem3.Text = "Attack";

			_comboAnimations = new ComboBox();
			_comboAnimations.Id = "_comboAnimations";
			_comboAnimations.Items.Add(listItem1);
			_comboAnimations.Items.Add(listItem2);
			_comboAnimations.Items.Add(listItem3);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_comboAnimations);

			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";

			var verticalStackPanel2 = new VerticalStackPanel();
			verticalStackPanel2.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel2.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel2.Widgets.Add(_labelFps);
			verticalStackPanel2.Widgets.Add(_labelMeshes);
			verticalStackPanel2.Widgets.Add(_labelCamera);

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(verticalStackPanel2);
		}

		
		public TextBox _textPath;
		public TextButton _buttonChange;
		public ComboBox _comboAnimations;
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
	}
}
