/* Generated by MyraPad at 10/11/2024 6:45:46 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace ModelViewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textPath = new TextBox();
			_textPath.Readonly = true;
			_textPath.Width = 300;
			_textPath.Id = "_textPath";

			var label1 = new Label();
			label1.Text = "Change...";

			_buttonChange = new Button();
			_buttonChange.Id = "_buttonChange";
			_buttonChange.Content = label1;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_textPath);
			horizontalStackPanel1.Widgets.Add(_buttonChange);

			var label2 = new Label();
			label2.Text = "Animation:";

			var label3 = new Label();

			var label4 = new Label();
			label4.Text = "Move";

			var label5 = new Label();
			label5.Text = "Attack";

			_comboAnimations = new ComboView();
			_comboAnimations.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboAnimations.Id = "_comboAnimations";
			Grid.SetColumn(_comboAnimations, 1);
			_comboAnimations.Widgets.Add(label3);
			_comboAnimations.Widgets.Add(label4);
			_comboAnimations.Widgets.Add(label5);

			var label6 = new Label();
			label6.Text = "Mode:";
			Grid.SetRow(label6, 1);

			var label7 = new Label();
			label7.Text = "Forward";

			var label8 = new Label();
			label8.Text = "Backward";

			_comboPlaybackMode = new ComboView();
			_comboPlaybackMode.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboPlaybackMode.Id = "_comboPlaybackMode";
			Grid.SetColumn(_comboPlaybackMode, 1);
			Grid.SetRow(_comboPlaybackMode, 1);
			_comboPlaybackMode.Widgets.Add(label7);
			_comboPlaybackMode.Widgets.Add(label8);

			var label9 = new Label();
			label9.Text = "Speed:";
			Grid.SetRow(label9, 2);

			_sliderSpeed = new HorizontalSlider();
			_sliderSpeed.Minimum = 0.1f;
			_sliderSpeed.Maximum = 3;
			_sliderSpeed.Value = 1;
			_sliderSpeed.Id = "_sliderSpeed";
			StackPanel.SetProportionType(_sliderSpeed, Myra.Graphics2D.UI.ProportionType.Fill);

			_labelSpeed = new Label();
			_labelSpeed.Text = "1.0";
			_labelSpeed.Width = 40;
			_labelSpeed.Id = "_labelSpeed";

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			Grid.SetColumn(horizontalStackPanel2, 1);
			Grid.SetRow(horizontalStackPanel2, 2);
			horizontalStackPanel2.Widgets.Add(_sliderSpeed);
			horizontalStackPanel2.Widgets.Add(_labelSpeed);

			var label10 = new Label();
			label10.Text = "Loop";

			_checkLoop = new CheckButton();
			_checkLoop.IsChecked = true;
			_checkLoop.CheckContentSpacing = 8;
			_checkLoop.Id = "_checkLoop";
			_checkLoop.Content = label10;

			var label11 = new Label();
			label11.Text = "Crossfade";

			_checkCrossfade = new CheckButton();
			_checkCrossfade.IsChecked = true;
			_checkCrossfade.CheckContentSpacing = 8;
			_checkCrossfade.Id = "_checkCrossfade";
			_checkCrossfade.Content = label11;

			var horizontalStackPanel3 = new HorizontalStackPanel();
			horizontalStackPanel3.Spacing = 8;
			Grid.SetRow(horizontalStackPanel3, 3);
			Grid.SetColumnSpan(horizontalStackPanel3, 2);
			horizontalStackPanel3.Widgets.Add(_checkLoop);
			horizontalStackPanel3.Widgets.Add(_checkCrossfade);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Pixels,
				Value = 300,
			});
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_comboAnimations);
			grid1.Widgets.Add(label6);
			grid1.Widgets.Add(_comboPlaybackMode);
			grid1.Widgets.Add(label9);
			grid1.Widgets.Add(horizontalStackPanel2);
			grid1.Widgets.Add(horizontalStackPanel3);

			var label12 = new Label();
			label12.Text = "Play";

			_buttonPlayStop = new Button();
			_buttonPlayStop.Width = 100;
			_buttonPlayStop.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Stretch;
			_buttonPlayStop.Id = "_buttonPlayStop";
			_buttonPlayStop.Content = label12;

			_sliderTime = new HorizontalSlider();
			_sliderTime.Width = 300;
			_sliderTime.Id = "_sliderTime";

			_labelTime = new Label();
			_labelTime.Text = "0.0";
			_labelTime.Id = "_labelTime";

			var horizontalStackPanel4 = new HorizontalStackPanel();
			horizontalStackPanel4.Spacing = 8;
			horizontalStackPanel4.Widgets.Add(_buttonPlayStop);
			horizontalStackPanel4.Widgets.Add(_sliderTime);
			horizontalStackPanel4.Widgets.Add(_labelTime);

			var label13 = new Label();
			label13.Text = "Bounding Boxes";

			_buttonBoundingBoxes = new ToggleButton();
			_buttonBoundingBoxes.Id = "_buttonBoundingBoxes";
			_buttonBoundingBoxes.Content = label13;

			var label14 = new Label();
			label14.Text = "Shadow Map";

			_buttonShadowMap = new ToggleButton();
			_buttonShadowMap.Id = "_buttonShadowMap";
			_buttonShadowMap.Content = label14;

			var horizontalStackPanel5 = new HorizontalStackPanel();
			horizontalStackPanel5.Spacing = 8;
			horizontalStackPanel5.Widgets.Add(_buttonBoundingBoxes);
			horizontalStackPanel5.Widgets.Add(_buttonShadowMap);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(grid1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel4);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel5);

			var label15 = new Label();
			label15.Text = "Effects Switches:";

			var label16 = new Label();
			label16.Text = "Draw Calls:";
			Grid.SetRow(label16, 1);

			var label17 = new Label();
			label17.Text = "Vertices Drawn:";
			Grid.SetRow(label17, 2);

			var label18 = new Label();
			label18.Text = "Primitives Drawn:";
			Grid.SetRow(label18, 3);

			var label19 = new Label();
			label19.Text = "Meshes Drawn:";
			Grid.SetRow(label19, 4);

			_labelEffectsSwitches = new Label();
			_labelEffectsSwitches.Text = "10";
			_labelEffectsSwitches.Id = "_labelEffectsSwitches";
			Grid.SetColumn(_labelEffectsSwitches, 1);

			_labelDrawCalls = new Label();
			_labelDrawCalls.Text = "10";
			_labelDrawCalls.Id = "_labelDrawCalls";
			Grid.SetColumn(_labelDrawCalls, 1);
			Grid.SetRow(_labelDrawCalls, 1);

			_labelVerticesDrawn = new Label();
			_labelVerticesDrawn.Text = "10";
			_labelVerticesDrawn.Id = "_labelVerticesDrawn";
			Grid.SetColumn(_labelVerticesDrawn, 1);
			Grid.SetRow(_labelVerticesDrawn, 2);

			_labelPrimitivesDrawn = new Label();
			_labelPrimitivesDrawn.Text = "10";
			_labelPrimitivesDrawn.Id = "_labelPrimitivesDrawn";
			Grid.SetColumn(_labelPrimitivesDrawn, 1);
			Grid.SetRow(_labelPrimitivesDrawn, 3);

			_labelMeshesDrawn = new Label();
			_labelMeshesDrawn.Text = "10";
			_labelMeshesDrawn.Id = "_labelMeshesDrawn";
			Grid.SetColumn(_labelMeshesDrawn, 1);
			Grid.SetRow(_labelMeshesDrawn, 4);

			_panelStatistics = new Grid();
			_panelStatistics.ColumnSpacing = 8;
			_panelStatistics.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			_panelStatistics.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			_panelStatistics.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			_panelStatistics.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			_panelStatistics.Left = -4;
			_panelStatistics.Id = "_panelStatistics";
			_panelStatistics.Widgets.Add(label15);
			_panelStatistics.Widgets.Add(label16);
			_panelStatistics.Widgets.Add(label17);
			_panelStatistics.Widgets.Add(label18);
			_panelStatistics.Widgets.Add(label19);
			_panelStatistics.Widgets.Add(_labelEffectsSwitches);
			_panelStatistics.Widgets.Add(_labelDrawCalls);
			_panelStatistics.Widgets.Add(_labelVerticesDrawn);
			_panelStatistics.Widgets.Add(_labelPrimitivesDrawn);
			_panelStatistics.Widgets.Add(_labelMeshesDrawn);

			
			Widgets.Add(verticalStackPanel1);
			Widgets.Add(_panelStatistics);
		}

		
		public TextBox _textPath;
		public Button _buttonChange;
		public ComboView _comboAnimations;
		public ComboView _comboPlaybackMode;
		public HorizontalSlider _sliderSpeed;
		public Label _labelSpeed;
		public CheckButton _checkLoop;
		public CheckButton _checkCrossfade;
		public Button _buttonPlayStop;
		public HorizontalSlider _sliderTime;
		public Label _labelTime;
		public ToggleButton _buttonBoundingBoxes;
		public ToggleButton _buttonShadowMap;
		public Label _labelEffectsSwitches;
		public Label _labelDrawCalls;
		public Label _labelVerticesDrawn;
		public Label _labelPrimitivesDrawn;
		public Label _labelMeshesDrawn;
		public Grid _panelStatistics;
	}
}
