/* Generated by MyraPad at 16.10.2019 1:18:11 */
using Myra.Graphics2D.UI;

#if !XENKO
using Microsoft.Xna.Framework;
#else
using Xenko.Core.Mathematics;
#endif

namespace ModelViewer.UI
{
	partial class MainPanel: Panel
	{
		private void BuildUI()
		{
			_textPath = new TextBox();
			_textPath.Text = "";
			_textPath.Readonly = true;
			_textPath.Id = "_textPath";
			_textPath.Width = 300;

			_buttonChange = new TextButton();
			_buttonChange.Text = "Change...";
			_buttonChange.Id = "_buttonChange";
			_buttonChange.GridColumn = 1;

			var listItem1 = new ListItem();
			listItem1.Id = null;
			listItem1.Text = "model1.g3dj";

			var listItem2 = new ListItem();
			listItem2.Id = null;
			listItem2.Text = "another_model.g3db";

			var listItem3 = new ListItem();
			listItem3.Id = null;
			listItem3.Text = "tree.g3dj";

			_listFiles = new ListBox();
			_listFiles.Id = "_listFiles";
			_listFiles.Height = 200;
			_listFiles.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listFiles.GridRow = 1;
			_listFiles.Items.Add(listItem1);
			_listFiles.Items.Add(listItem2);
			_listFiles.Items.Add(listItem3);

			var listItem4 = new ListItem();
			listItem4.Id = null;

			var listItem5 = new ListItem();
			listItem5.Id = null;
			listItem5.Text = "Move";

			var listItem6 = new ListItem();
			listItem6.Id = null;
			listItem6.Text = "Attack";

			_comboAnimations = new ComboBox();
			_comboAnimations.Id = "_comboAnimations";
			_comboAnimations.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboAnimations.GridRow = 2;
			_comboAnimations.Items.Add(listItem4);
			_comboAnimations.Items.Add(listItem5);
			_comboAnimations.Items.Add(listItem6);

			_checkLightning = new CheckBox();
			_checkLightning.Text = "Lightning On";
			_checkLightning.Id = "_checkLightning";
			_checkLightning.GridRow = 3;

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultColumnProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.Widgets.Add(_textPath);
			grid1.Widgets.Add(_buttonChange);
			grid1.Widgets.Add(_listFiles);
			grid1.Widgets.Add(_comboAnimations);
			grid1.Widgets.Add(_checkLightning);

			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel1.Widgets.Add(_labelFps);
			verticalStackPanel1.Widgets.Add(_labelMeshes);
			verticalStackPanel1.Widgets.Add(_labelCamera);

			
			Widgets.Add(grid1);
			Widgets.Add(verticalStackPanel1);
		}

		
		public TextBox _textPath;
		public TextButton _buttonChange;
		public ListBox _listFiles;
		public ComboBox _comboAnimations;
		public CheckBox _checkLightning;
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
	}
}