/* Generated by MyraPad at 8/31/2024 12:31:49 AM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace NursiaEditor.UI
{
	partial class AddNewItemDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Name:";

			_textName = new TextBox();
			_textName.Id = "_textName";
			StackPanel.SetProportionType(_textName, Myra.Graphics2D.UI.ProportionType.Fill);

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(label1);
			horizontalStackPanel1.Widgets.Add(_textName);

			var label2 = new Label();
			label2.Text = "Item 1";

			var radioButton1 = new RadioButton();
			radioButton1.Content = label2;

			var label3 = new Label();
			label3.Text = "Item 2";

			var radioButton2 = new RadioButton();
			radioButton2.Content = label3;

			var label4 = new Label();
			label4.Text = "Item 3";

			var radioButton3 = new RadioButton();
			radioButton3.Content = label4;

			_itemsPanel = new VerticalStackPanel();
			_itemsPanel.Spacing = 4;
			_itemsPanel.Id = "_itemsPanel";
			_itemsPanel.Widgets.Add(radioButton1);
			_itemsPanel.Widgets.Add(radioButton2);
			_itemsPanel.Widgets.Add(radioButton3);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_itemsPanel);

			
			Title = "Add New Scene";
			Left = 808;
			Top = 247;
			Width = 300;
			Content = verticalStackPanel1;
		}

		
		public TextBox _textName;
		public VerticalStackPanel _itemsPanel;
	}
}
