/* Generated by MyraPad at 9/24/2024 8:56:39 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace NursiaEditor.UI
{
	partial class ChooseAssetDialog: Dialog
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Name:";

			_textName = new TextBox();
			_textName.Id = "_textName";
			Grid.SetColumn(_textName, 1);

			var label2 = new Label();
			label2.Text = "Model:";
			Grid.SetRow(label2, 1);

			var label3 = new Label();
			label3.Text = "Model.glb";

			_comboModels = new ComboView();
			_comboModels.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_comboModels.Id = "_comboModels";
			Grid.SetColumn(_comboModels, 1);
			Grid.SetRow(_comboModels, 1);
			_comboModels.Widgets.Add(label3);

			var grid1 = new Grid();
			grid1.ColumnSpacing = 8;
			grid1.RowSpacing = 8;
			grid1.DefaultRowProportion = new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			};
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			grid1.ColumnsProportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			grid1.Widgets.Add(label1);
			grid1.Widgets.Add(_textName);
			grid1.Widgets.Add(label2);
			grid1.Widgets.Add(_comboModels);

			
			Title = "Add New Model";
			Left = 373;
			Top = 270;
			Width = 500;
			Content = grid1;
		}

		
		public TextBox _textName;
		public ComboView _comboModels;
	}
}
