/* Generated by MyraPad at 18.09.2019 22:41:37 */
using Myra.Graphics2D.UI;

namespace NursiaStudio.UI
{
	public partial class MainForm: Grid
	{
		public MainForm()
		{
			BuildUI();

			_topSplitPane.SetSplitterPosition(0, 0.3f);
			_topSplitPane.SetSplitterPosition(1, 0.7f);
		}
	}
}