/* Generated by MyraPad at 8/31/2023 11:38:00 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;

namespace Nursia.Samples.LevelEditor.UI
{
	partial class MainForm: VerticalStackPanel
	{
		private void BuildUI()
		{
			_menuItemQuit = new MenuItem();
			_menuItemQuit.Text = "&Quit";
			_menuItemQuit.Id = "_menuItemQuit";

			var menuItem1 = new MenuItem();
			menuItem1.Text = "&File";
			menuItem1.Items.Add(_menuItemQuit);

			_menuItemAddModel = new MenuItem();
			_menuItemAddModel.Text = "&Model";
			_menuItemAddModel.Id = "_menuItemAddModel";

			_menuItemAddSkybox = new MenuItem();
			_menuItemAddSkybox.Text = "&Skybox";
			_menuItemAddSkybox.Id = "_menuItemAddSkybox";

			_menuItemAddTerrain = new MenuItem();
			_menuItemAddTerrain.Text = "&Terrain";
			_menuItemAddTerrain.Id = "_menuItemAddTerrain";

			_menuItemAddWater = new MenuItem();
			_menuItemAddWater.Text = "&Water";
			_menuItemAddWater.Id = "_menuItemAddWater";

			var menuItem2 = new MenuItem();
			menuItem2.Text = "&Items";
			menuItem2.Items.Add(_menuItemAddModel);
			menuItem2.Items.Add(_menuItemAddSkybox);
			menuItem2.Items.Add(_menuItemAddTerrain);
			menuItem2.Items.Add(_menuItemAddWater);

			_menuItemShowGrid = new MenuItem();
			_menuItemShowGrid.Text = "&Grid";
			_menuItemShowGrid.Id = "_menuItemShowGrid";

			_menuItemLockFps = new MenuItem();
			_menuItemLockFps.Text = "&Lock FPS at 60";
			_menuItemLockFps.Id = "_menuItemLockFps";

			var menuItem3 = new MenuItem();
			menuItem3.Text = "&Options";
			menuItem3.Items.Add(_menuItemShowGrid);
			menuItem3.Items.Add(_menuItemLockFps);

			_menuItemAbout = new MenuItem();
			_menuItemAbout.Text = "&About";
			_menuItemAbout.Id = "_menuItemAbout";

			var menuItem4 = new MenuItem();
			menuItem4.Text = "&Help";
			menuItem4.Items.Add(_menuItemAbout);

			var horizontalMenu1 = new HorizontalMenu();
			horizontalMenu1.Items.Add(menuItem1);
			horizontalMenu1.Items.Add(menuItem2);
			horizontalMenu1.Items.Add(menuItem3);
			horizontalMenu1.Items.Add(menuItem4);

			_labelFps = new Label();
			_labelFps.Text = "FPS: 60.0";
			_labelFps.Id = "_labelFps";

			_labelMeshes = new Label();
			_labelMeshes.Text = "Meshes: 15";
			_labelMeshes.Id = "_labelMeshes";

			_labelCamera = new Label();
			_labelCamera.Text = "Camera: 0/50/0;270;0";
			_labelCamera.Id = "_labelCamera";

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Right;
			verticalStackPanel1.VerticalAlignment = Myra.Graphics2D.UI.VerticalAlignment.Bottom;
			verticalStackPanel1.Widgets.Add(_labelFps);
			verticalStackPanel1.Widgets.Add(_labelMeshes);
			verticalStackPanel1.Widgets.Add(_labelCamera);

			_panelScene = new Panel();
			_panelScene.Id = "_panelScene";
			_panelScene.Widgets.Add(verticalStackPanel1);

			var listItem1 = new ListItem();
			listItem1.Text = "Directional Light (#_sun)";

			var listItem2 = new ListItem();
			listItem2.Text = "Camera (#_mainCamera)";

			var listItem3 = new ListItem();
			listItem3.Text = "Terrain (#_terrain)";

			var listItem4 = new ListItem();
			listItem4.Text = "Water (#_water)";

			_listExplorer = new ListBox();
			_listExplorer.HorizontalAlignment = Myra.Graphics2D.UI.HorizontalAlignment.Stretch;
			_listExplorer.Id = "_listExplorer";
			_listExplorer.Items.Add(listItem1);
			_listExplorer.Items.Add(listItem2);
			_listExplorer.Items.Add(listItem3);
			_listExplorer.Items.Add(listItem4);

			_panelProperties = new Panel();
			_panelProperties.Id = "_panelProperties";

			var verticalSplitPane1 = new VerticalSplitPane();
			verticalSplitPane1.Widgets.Add(_listExplorer);
			verticalSplitPane1.Widgets.Add(_panelProperties);

			_topSplitPane = new HorizontalSplitPane();
			_topSplitPane.Id = "_topSplitPane";
			_topSplitPane.Widgets.Add(_panelScene);
			_topSplitPane.Widgets.Add(verticalSplitPane1);

			var panel1 = new Panel();
			panel1.Widgets.Add(_topSplitPane);

			
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Auto,
			});
			Proportions.Add(new Proportion
			{
				Type = Myra.Graphics2D.UI.ProportionType.Fill,
			});
			Widgets.Add(horizontalMenu1);
			Widgets.Add(panel1);
		}

		
		public MenuItem _menuItemQuit;
		public MenuItem _menuItemAddModel;
		public MenuItem _menuItemAddSkybox;
		public MenuItem _menuItemAddTerrain;
		public MenuItem _menuItemAddWater;
		public MenuItem _menuItemShowGrid;
		public MenuItem _menuItemLockFps;
		public MenuItem _menuItemAbout;
		public Label _labelFps;
		public Label _labelMeshes;
		public Label _labelCamera;
		public Panel _panelScene;
		public ListBox _listExplorer;
		public Panel _panelProperties;
		public HorizontalSplitPane _topSplitPane;
	}
}
